language: rust
rust: nightly
os: linux
dist: xenial
cache:
    directories:
        - $HOME/.cargo
        - randomprime/target
        - build/randomprime/x86_64-unknown-linux-gnu
        - build/randomprime/powerpc-unknown-linux-gnu
branches:
    except:
        - continuous
before_cache:
      - rm -rfv ../randomprime/target/debug/incremental/{randomprime,build_script_build}-*
      - rm -rfv ../randomprime/target/debug/.fingerprint/randomprime-*
      - rm -rfv ../randomprime/target/debug/build/randomprime-*
      - rm -rfv ../randomprime/target/debug/deps/librandomprime-*
      - rm -rfv ../randomprime/target/debug/deps/randomprime-*
      - rm -rfv ../randomprime/target/debug/{randomprime,librandomprime}.d
      - rm -rfv ../build/randomprime/x86_64-unknown-linux-gnu/debug/incremental/{randomprime,build_script_build}-*
      - rm -rfv ../build/randomprime/x86_64-unknown-linux-gnu/debug/.fingerprint/randomprime-*
      - rm -rfv ../build/randomprime/x86_64-unknown-linux-gnu/debug/build/randomprime-*
      - rm -rfv ../build/randomprime/x86_64-unknown-linux-gnu/debug/deps/librandomprime-*
      - rm -rfv ../build/randomprime/x86_64-unknown-linux-gnu/debug/deps/randomprime-*
      - rm -rfv ../build/randomprime/x86_64-unknown-linux-gnu/debug/{randomprime,librandomprime}.d
      - rm -rfv ../build/randomprime/powerpc-unknown-linux-gnu/debug/incremental/{randomprime,build_script_build}-*
      - rm -rfv ../build/randomprime/powerpc-unknown-linux-gnu/release/.fingerprint/randomprime-*
      - rm -rfv ../build/randomprime/powerpc-unknown-linux-gnu/release/build/randomprime-*
      - rm -rfv ../build/randomprime/powerpc-unknown-linux-gnu/release/deps/librandomprime-*
      - rm -rfv ../build/randomprime/powerpc-unknown-linux-gnu/release/deps/randomprime-*
      - rm -rfv ../build/randomprime/powerpc-unknown-linux-gnu/release/{randomprime,librandomprime}.d
      - cargo clean -p ../randomprime
      - cargo clean -p ../build/randomprime
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt-5.14.1-xenial -y
    - sudo apt-get update -qq
install:
    - sudo apt-get -y install qt514base qt514webengine qt514tools qt514svg qt514translations libgl1-mesa-dev
    - source /opt/qt*/bin/qt*-env.sh
before_script:
    - rustup target add --toolchain nightly powerpc-unknown-linux-gnu
    - sudo cp /opt/qt*/bin/qhelpgenerator /bin/
    - source ~/.bashrc
script:
    - cd randomprime
    - cargo build --release
    - cd ../build
    - cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib
    - cmake --build . --target all -j $(nproc)
    - make DESTDIR=appdir -j$(nproc) install ; find appdir/
    - find $TRAVIS_BUILD_DIR \( -name "moc_*" -or -name "*.o" -or -name "qrc_*" -or -name "Makefile*" -or -name "*.a" \) -exec rm {} \;
    - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
    - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
    - export VERSION=0.2
    - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage -verbose=2 -bundle-non-qt-libs -qmake=/opt/qt514/bin/qmake -extra-plugins=iconengines/libqsvgicon.so,platformthemes/libqgtk3.so
after_success:
  # find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq # for debugging
  # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Metroid_Prime_Door_Randomizer*.AppImage*
env: CC=gcc-7 CXX=g++-7
